[env:nodemcuv2]
platform = espressif8266
board = nodemcuv2
framework = arduino
monitor_speed = 115200
build_flags = -D FIRMWARE_VERSION='"1.1.0"'
test_build_src = true
lib_deps =
    tzapu/WiFiManager
    bblanchon/ArduinoJson@5.13.4
    knolleary/PubSubClient@^2.8
    adafruit/Adafruit BME280 Library@^2.2.4
    adafruit/Adafruit Unified Sensor@^1.1.14
    adafruit/DHT sensor library@^1.4.6
